trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet --info
  displayName: 'Show .NET Info'

- script: dotnet build
  displayName: 'Build'